infrastructure {
    cloud {
        aws {
            region = "us_east_1";
            secret = ${AWS_SECRET};
        }
    }
    monitoring {
        enabled = true;
        api_key = ${MONITOR_API_KEY};
    }
}
